/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rfs.h"
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>

/* Handle para las llamadas remotas (creado/asignado en rfs_1() */
CLIENT *clnt;

/* Crea/asigna el handle */
void rfs_1(char *host) {
#ifndef DEBUG
    clnt = clnt_create (host, RFS, RFS_VERS_1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif /* DEBUG */
}

/* Destruye el handle */
void rfs_1_end() {
#ifndef DEBUG
    clnt_destroy (clnt);
#endif /* DEBUG */
}

/* Wrapper para rfs_open */
int wrap_rfs_open(char *file_name, int flags) {
    open_record rfs_open_1_arg;
    int *result_1;
    /* define archivo a leer */
    rfs_open_1_arg.file_name = file_name; 
    /* define permisos */
    rfs_open_1_arg.flags = flags;
    result_1 = rfs_open_1(&rfs_open_1_arg, clnt);
    if (result_1 == (int *) NULL)
        clnt_perror (clnt, "Fallo llamada open");
    return *result_1;
}

/* Wrapper para rfs_read */
file_data *wrap_rfs_read(int fd, int count) {
    read_record rfs_read_1_arg;
    file_data *result_2;
    rfs_read_1_arg.fd = fd;
    rfs_read_1_arg.count = count;

    result_2 = rfs_read_1(&rfs_read_1_arg, clnt);
    if (result_2 == (file_data *) NULL)
        clnt_perror (clnt, "Fallo llamada read");
    return result_2;
}

/* Wrapper para rfs_close */
int wrap_rfs_close(int fd) {
    int *result_3;
    int rfs_close_1_arg = fd;
    result_3 = rfs_close_1(&rfs_close_1_arg, clnt);
    if (result_3 == (int *) NULL) {
        clnt_perror (clnt, "Fallo llamada close");
    }
    return *result_3;
}

/*Wrapper para rfs_write*/
int wrap_rfs_write(write_record *r) {
    int *result_4;
    result_4 = rfs_write_1(r, clnt);
    if (result_4 == (int *) NULL) {
        clnt_perror(clnt, "Fallo llamada write");
    }
    return *(int *)result_4;
}


int main (int argc, char *argv[]) {
    char *host;
    char *file_name;
    int fd, n;
    file_data *result_2;
    char *write_file = "un_archivo_escrito.txt";
    char *cadena = "una cadena para escribir en el archivo\n";
    write_record wr;
    /* Se deben pasar nombre de host y de archivo => argc=3 */
    if (argc < 3) {
        printf ("usage: %s server_host filename\n", argv[0]);
        exit (1);
    }
    host = argv[1];
    rfs_1 (host);
    /* nombre del host remoto */
    /* creacion/asignacion del handle */
    file_name = argv[2];
    /* nombre del archivo a abrir/leer */
    fd = wrap_rfs_open(file_name, O_RDWR);
    int otro_fd = wrap_rfs_open(write_file, O_RDWR | O_CREAT | O_TRUNC);

    if (fd == -1 || otro_fd == -1) {
        printf("Error al abrir el archivo\n");
        return 1;
    }

    /*Cargamos el registro para escribir un archivo*/
    wr.fd = otro_fd;
    wr.buf.file_data_val = (char *)malloc(sizeof(char) * (strlen(cadena)+1));
    strcpy(wr.buf.file_data_val, cadena);
    wr.buf.file_data_len = strlen(cadena);

    if((n = wrap_rfs_write(&wr)) == -1) {
        printf("Error al escribrir\n");
        return 1;
    }

    /*do {*/
        /*[> lecturas/uso del archivo <]*/
        /*result_2 = wrap_rfs_read(fd, 20);*/
        /*for (n = 0; n < result_2->file_data_len; ++n)*/
        /*putchar(result_2->file_data_val[n]);*/
    /*} while (result_2->file_data_len == 20);*/
    /*putchar('\n');*/
    wrap_rfs_close(fd);
    wrap_rfs_close(otro_fd);
    rfs_1_end();
    exit (0);
    /* cierre del archivo */
    /* destruccion del handle */
}
