version: '3'
services:
  node-red:
    container_name: "node-red"
    ports:
      - "1880:1880"
    image: "nodered/node-red-docker"
    restart: "always"
    networks:
      iota:
        ipv4_address: 128.80.0.20
  mosquitto-broker:
    container_name: "mosquitto-broker"
    ports:
      - "1883:1883"
      - "9001:9001"
    image: "eclipse-mosquitto"
    restart: "always"
    networks:
      iota:
        ipv4_address: 128.80.0.10

networks:
  iota:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 128.80.0.0/24
