all:
	javac -cp src/ -d bin/ src/**/*.java

gui:
	javac -cp src/ -d bin/ src/rfs/MainCliente.java src/rfs/MainServidor.java

cli:
	javac -cp src/ -d bin/ src/rfs/CLICliente.java src/rfs/MainServidor.java

clean:
	rm -rf bin/*
